dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t journalnodejs .
      - docker images
      - docker tag journalnodejs $DOCKER_USERNAME/journalnodejs:v1
      - docker push $DOCKER_USERNAME/journalnodejs:v1
      
    - stage: test
      script:
      - docker run $DOCKER_USERNAME/journalnodejs echo "This is a sample text" > hello.txt
      - cat hello.txt
      - docker ps -a
