dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t journalnodejs .
      - docker images
      - docker tag journalnodejs $DOCKER_USERNAME/journalnodejs:"$TRAVIS_BUILD_ID"
      - docker push $DOCKER_USERNAME/journalnodejs:"$TRAVIS_BUILD_ID"
          
    - stage: openshift cluster 
      script:
       - wget https://mirror.openshift.com/pub/openshift-v4/amd64/clients/oc-dec2/4.6/linux/oc.tar.gz
       - tar -xzf oc.tar.gz
       - sudo -E env "PATH=$PATH" cp oc /bin
       - sudo -E env "PATH=$PATH" cp oc /usr/bin
       - sudo -E env "PATH=$PATH" chmod a+x /usr/bin/oc
       - sudo -E env "PATH=$PATH" chmod a+x /bin/oc
       - oc login --token="$OC_TOKEN" --server="$OC_SERVER" 
       - oc project "$PROJECT_NAME"
       - git config user.email sourabh.h51@gmail.com
       - git config user.name sourabh1500
       - git clone https://$user:$encodedPass@github.com/$user/journal_nodejs_cd.git
       - echo $TRAVIS_BUILD_NUMBER
       - envsubst < deployment.yaml.template > deployment.yaml
       - oc apply -f deployment.yaml
       - cat deployment.yaml
       - git add .
       - git commit -m 'done by travis node-app-update-deployment-pipeline'
       - git push https://$user:$encodedPass@github.com/$user/journal_nodejs_cd.git HEAD:main
