dist: trusty

env:
 global:
   -SHA = $(git rev-parse HEAD)
   
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t journalnodejs .
      - docker images
      - docker tag journalnodejs $DOCKER_USERNAME/journalnodejs:${SHA}
      - docker push $DOCKER_USERNAME/journalnodejs:${SHA}
      
    - stage: test
      script:
      - docker run $DOCKER_USERNAME/journalnodejs echo "This is a sample text" > hello.txt
      - cat hello.txt
      - docker ps -a
