dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t journalnodejs .
      - docker images
      - docker tag journalnodejs $DOCKER_USERNAME/journalnodejs:"$TRAVIS_BUILD_NUMBER"
      - docker push $DOCKER_USERNAME/journalnodejs:"$TRAVIS_BUILD_NUMBER"
          
    - stage: replace the tag name 
      script:
       - git config user.email sourabh.h51@gmail.com
       - git config user.name sourabh1500
       - git clone https://$user:$encodedPass@github.com/$user/journal_nodejs.git
       - cat nodejs.yaml
       - echo $TRAVIS_BUILD_NUMBER
       - sed -i 's/latest/'"$TRAVIS_BUILD_NUMBER"'/g' ./nodejs.yaml
#        - sed -i 's+$DOCKER_USERNAME/journalnodejs:.*+$DOCKER_USERNAME/journalnodejs:"$TRAVIS_BUILD_NUMBER"+g'
       - cat nodejs.yaml
       - git add .
       - git commit -m 'done by travis node-app-update-deployment-pipeline'
       - git push https://$user:$encodedPass@github.com/$user/journal_nodejs.git HEAD:main
       - wget https://mirror.openshift.com/pub/openshift-v4/amd64/clients/oc-dec2/4.6/linux/oc.tar.gz
       - tar -xzf oc.tar.gz
       - sudo -E env "PATH=$PATH" cp oc /bin
       - sudo -E env "PATH=$PATH" cp oc /usr/bin
       - sudo -E env "PATH=$PATH" chmod a+x /usr/bin/oc
       - sudo -E env "PATH=$PATH" chmod a+x /bin/oc
       - oc login --token="$OC_TOKEN" --server="$OC_SERVER" 
       - oc project "$PROJECT_NAME"
       - oc apply -f nodejs.yaml
